### PR TITLE
Improve convertUidToCType for DCEs with identifier

### PR DESCRIPTION
**Pull request by luisbecker-gh**

### CODE REVIEW

**Comment by a-r-m-i-n** [comment]
Hi. I guess you've improved the method to fix the ImportExport Hook?

**Comment by luisbecker-gh** [comment]
@a-r-m-i-n Exactly, i think it is the only use of this method.

I have the problem that an DCE with the identifier "card" and the resulting CType "dce_card", an imported Content Element gets the CType "dce_dceuid5".

It gets imported with the correct CType, maybe the ImportExport Hook doesnt need to set the CType again?

**Comment by a-r-m-i-n** [comment]
Maybe... I'm also not sure about that. But I would keep it as it is, because it works and I don't want to debug the ImpExp module 😅

But I'm going to merge your PR.

Thanks!

**Comment by luisbecker-gh** [comment]
Thank you!

**Pull request merged**
